package us.cmcc.sms.cleaner.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BLACK_WORD.
 */
public class BlackWord {

    private Long id;
    /** Not-null value. */
    private String word;
    private String mark;

    public BlackWord() {
    }

    public BlackWord(Long id) {
        this.id = id;
    }

    public BlackWord(Long id, String word, String mark) {
        this.id = id;
        this.word = word;
        this.mark = mark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getWord() {
        return word;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWord(String word) {
        this.word = word;
    }

    public String getMark() {
        return mark;
    }

    public void setMark(String mark) {
        this.mark = mark;
    }

}
