package us.cmcc.sms.cleaner.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.text.TextUtils;

/**
 * Entity mapped to table BLACK_NUMBER.
 */
public class BlackNumber {

    private Long id;
    /** Not-null value. */
    private String number;
    private String mark;

    public BlackNumber() {
    }

    public BlackNumber(Long id) {
        this.id = id;
    }

    public BlackNumber(Long id, String number, String mark) {
        this.id = id;
        this.number = number;
        this.mark = mark;
    }

    public BlackNumber(String number, String mark) {
        this.number = number;
        this.mark = mark;
    }
    @Override
    public String toString() {
        if (TextUtils.isEmpty(mark)) {
            return number;
        } else {
            return mark + "(" + number + ")";
        }
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNumber() {
        return number;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNumber(String number) {
        this.number = number;
    }

    public String getMark() {
        return mark;
    }

    public void setMark(String mark) {
        this.mark = mark;
    }

}
