package us.cmcc.sms.cleaner.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import us.cmcc.sms.cleaner.dao.WhiteNumber;
import us.cmcc.sms.cleaner.dao.WhiteWord;
import us.cmcc.sms.cleaner.dao.BlackNumber;
import us.cmcc.sms.cleaner.dao.BlackWord;
import us.cmcc.sms.cleaner.dao.SmsDir;
import us.cmcc.sms.cleaner.dao.ThreadDir;

import us.cmcc.sms.cleaner.dao.WhiteNumberDao;
import us.cmcc.sms.cleaner.dao.WhiteWordDao;
import us.cmcc.sms.cleaner.dao.BlackNumberDao;
import us.cmcc.sms.cleaner.dao.BlackWordDao;
import us.cmcc.sms.cleaner.dao.SmsDirDao;
import us.cmcc.sms.cleaner.dao.ThreadDirDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig whiteNumberDaoConfig;
    private final DaoConfig whiteWordDaoConfig;
    private final DaoConfig blackNumberDaoConfig;
    private final DaoConfig blackWordDaoConfig;
    private final DaoConfig smsDirDaoConfig;
    private final DaoConfig threadDirDaoConfig;

    private final WhiteNumberDao whiteNumberDao;
    private final WhiteWordDao whiteWordDao;
    private final BlackNumberDao blackNumberDao;
    private final BlackWordDao blackWordDao;
    private final SmsDirDao smsDirDao;
    private final ThreadDirDao threadDirDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        whiteNumberDaoConfig = daoConfigMap.get(WhiteNumberDao.class).clone();
        whiteNumberDaoConfig.initIdentityScope(type);

        whiteWordDaoConfig = daoConfigMap.get(WhiteWordDao.class).clone();
        whiteWordDaoConfig.initIdentityScope(type);

        blackNumberDaoConfig = daoConfigMap.get(BlackNumberDao.class).clone();
        blackNumberDaoConfig.initIdentityScope(type);

        blackWordDaoConfig = daoConfigMap.get(BlackWordDao.class).clone();
        blackWordDaoConfig.initIdentityScope(type);

        smsDirDaoConfig = daoConfigMap.get(SmsDirDao.class).clone();
        smsDirDaoConfig.initIdentityScope(type);

        threadDirDaoConfig = daoConfigMap.get(ThreadDirDao.class).clone();
        threadDirDaoConfig.initIdentityScope(type);

        whiteNumberDao = new WhiteNumberDao(whiteNumberDaoConfig, this);
        whiteWordDao = new WhiteWordDao(whiteWordDaoConfig, this);
        blackNumberDao = new BlackNumberDao(blackNumberDaoConfig, this);
        blackWordDao = new BlackWordDao(blackWordDaoConfig, this);
        smsDirDao = new SmsDirDao(smsDirDaoConfig, this);
        threadDirDao = new ThreadDirDao(threadDirDaoConfig, this);

        registerDao(WhiteNumber.class, whiteNumberDao);
        registerDao(WhiteWord.class, whiteWordDao);
        registerDao(BlackNumber.class, blackNumberDao);
        registerDao(BlackWord.class, blackWordDao);
        registerDao(SmsDir.class, smsDirDao);
        registerDao(ThreadDir.class, threadDirDao);
    }
    
    public void clear() {
        whiteNumberDaoConfig.getIdentityScope().clear();
        whiteWordDaoConfig.getIdentityScope().clear();
        blackNumberDaoConfig.getIdentityScope().clear();
        blackWordDaoConfig.getIdentityScope().clear();
        smsDirDaoConfig.getIdentityScope().clear();
        threadDirDaoConfig.getIdentityScope().clear();
    }

    public WhiteNumberDao getWhiteNumberDao() {
        return whiteNumberDao;
    }

    public WhiteWordDao getWhiteWordDao() {
        return whiteWordDao;
    }

    public BlackNumberDao getBlackNumberDao() {
        return blackNumberDao;
    }

    public BlackWordDao getBlackWordDao() {
        return blackWordDao;
    }

    public SmsDirDao getSmsDirDao() {
        return smsDirDao;
    }

    public ThreadDirDao getThreadDirDao() {
        return threadDirDao;
    }

}
