package us.cmcc.sms.cleaner.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SMS_DIR.
 */
public class SmsDir {

    private Long id;
    /** Not-null value. */
    private String name;

    public SmsDir() {
    }

    public SmsDir(Long id) {
        this.id = id;
    }

    public SmsDir(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

}
